version: "3"

services:
  server:
    image: srcrs/magicbox:latest
    container_name: MagicBox
    volumes:
      - "$PWD/configs:/app/configs"
      - "$PWD/MagicTask.log:/app/MagicTask.log"
    environment:
      - "TZ=Asia/Shanghai"