hostloc:
  users:
    doduo:
      username: ''
      password: ''
      cron: '0 41 8,16 * * *'
  task:
    accessSpace: 10
    notify: ''
    filersUser: "Cat, 咯拉无米, 小新, 137405406, 欧阳逍遥, temp, 我是人, zyypp, ailywen, bbkktt, llyjone, cheng"
    multiThread: false
